apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinfo
  labels:
    app: myinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myinfo
  template:
    metadata:
      labels:
        app: myinfo
    spec:
      containers:
        - name: myinfo
          image: "username/myinfo:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
